"""empty message

Revision ID: 30066ed2e97
Revises: None
Create Date: 2014-12-11 13:46:25.408416

"""

# revision identifiers, used by Alembic.
revision = '30066ed2e97'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.LargeBinary(length=64), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('ntime', sa.DateTime(), nullable=False),
    sa.Column('orphan', sa.Boolean(), nullable=True),
    sa.Column('total_in', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.Column('total_out', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('algo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.LargeBinary(length=64), nullable=True),
    sa.Column('network_fee', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.Column('coinbase', sa.Boolean(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('total_in', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.Column('total_out', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txid')
    )
    op.create_table('output',
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('origin_tx_hash', sa.LargeBinary(length=64), nullable=False),
    sa.Column('amount', lincoln.model_lib.SqliteNumeric(precision=1000, scale=28), nullable=True),
    sa.Column('index', sa.SmallInteger(), nullable=False),
    sa.Column('dest_address', sa.LargeBinary(), nullable=True),
    sa.Column('spend_tx_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['origin_tx_hash'], ['transaction.txid'], ),
    sa.ForeignKeyConstraint(['spend_tx_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('origin_tx_hash', 'index')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('output')
    op.drop_table('transaction')
    op.drop_table('block')
    ### end Alembic commands ###
